export const GET_LIST_BANNERS = "GET_LIST_BANNERS";
export const GET_LIST_FILMS = "GET_LIST_FILMS";
export const GET_PHIM_DANG_CHIEU = "GET_PHIM_DANG_CHIEU";
export const GET_PHIM_SAP_CHIEU = "GET_PHIM_SAP_CHIEU";
export const GET_TAT_CA_PHIM = "GET_TAT_CA_PHIM";
export const GET_ONE_FILM = "GET_ONE_FILM";
